tags/urls.py
from django.conf.urls import url

from . import views

app_name = 'tags'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'tags/create$', views.create_tag, name='create-tag'),
    url(r'tags/(?P<tag_id>[0-9]+)/delete$', views.delete_tag, name='delete-tag'),
    url(r'tags/(?P<tag_id>[0-9]+)/name/update$', views.update_tag_name, name='update-tag-name'),
    url(r'tags/(?P<tag_id>[0-9]+)/color/update/(?P<color_id>[0-9]+)$', views.update_tag_color, name='update-tag-color'),
    url(r'notes/(?P<note_id>[0-9]+)/tags/(?P<tag_id>[0-9]+)/remove$', views.remove_note_tag, name='remove-note-tag'),
    url(r'notes/(?P<note_id>[0-9]+)/delete$', views.delete_note, name='delete-note'),
]

tagssite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tags.urls')),
]

tags/models.py
import re

from django.core.validators import MaxValueValidator
from django.db import models
from django.forms import ValidationError
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Color(models.Model):
	hex = models.PositiveIntegerField(validators=[MaxValueValidator(16777215)])

	def __str__(self):
		return '#' + '{:06x}'.format(self.hex)

@python_2_unicode_compatible
class Tag(models.Model):
	name = models.CharField(max_length=50, unique=True)
	color = models.ForeignKey(Color, on_delete=models.SET_DEFAULT, default=1)

	class Meta:
		ordering = ['name']

	def __str__(self):
		return self.name

	def clean(self):
		self.name = self.name.replace(" ", "").lower()

class Note(models.Model):
	creation_date = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=100, blank=True)
	text = models.CharField(max_length=1000, blank=True)
	link = models.TextField(blank=True)
	tags = models.ManyToManyField(Tag)

	def clean(self):
		self.title = self.title.strip()
		self.link = self.link.strip()
		if self.title is None and self.text is None and self.link is None:
			raise ValidationError('Your note is empty')

tags/forms.py
from django.forms import CharField
from django.forms import ModelForm

from .models import Note
from .models import Tag

class TagForm(ModelForm):
	class Meta:
		model = Tag
		fields = ['name']
		error_messages = {
			'name': {
				'required': 'Please, give a name to the tag.',
				'unique': 'This tag already exists.'
			}
		}

class NoteForm(ModelForm):
	class Meta:
		model = Note
		fields = ['title', 'text', 'link']

tags/views.py
import json

from django.contrib.auth import authenticate, login
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import render, redirect,get_object_or_404
from django.template.loader import render_to_string
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_GET
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from .models import Color
from .models import Note
from .models import Tag
from .forms import NoteForm
from .forms import TagForm
from .decorators import require_ajax

# HTTP status code:
# 400: invalid form; 409: desync

# How to get notes_ids related to some tag:
#notes_ids = []
#if tag.note_set:
#	notes_ids = list(tag.note_set.all().values_list('id', flat=True))

@require_GET
@ensure_csrf_cookie
def index(request):
	#if request.user.is_authenticated:
	context = {
		'color_list': Color.objects.all(),
		'tag_list': Tag.objects.all(), 
		'note_list': Note.objects.all()
	}
	return render(
		request, 
		'tags/index.html', 
		context)
	#else:
		#return render(
			#request, 
			#'tags/login.html')

#def create

def login(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(request, username=username, password=password)
	if user is not None:
		login(request, user)
		return redirect('tags:index')
	else:
		pass


@require_POST
@require_ajax
def create_tag(request):
	form = TagForm(request.POST)
	if form.is_valid():
		tag = form.save()
		try:
			color = Color.objects.get(pk=request.POST.get('color'))
			tag.color = color
			tag.save()
		except:
			pass
		return render(
			request, 
			'tags/tag_list.html', 
			context={'color_list': Color.objects.all(), 'tag_list': Tag.objects.all()})
	else:
		return JsonResponse(json.loads(form.errors.as_json()), status=400)

@require_POST
@require_ajax
def delete_tag(request, tag_id):
	try:
		tag = Tag.objects.get(pk=tag_id)
	except Tag.DoesNotExist:
		return render(
			request, 
			'tags/tag_list.html', 
			context={'color_list': Color.objects.all(), 'tag_list': Tag.objects.all()}, 
			status=409)
	else:
		tag.delete()
		return JsonResponse({'tag_id': tag_id})

@require_POST
@require_ajax
def update_tag_color(request, tag_id, color_id):
	try:
		tag = Tag.objects.get(pk=tag_id)
		color = Color.objects.get(pk=color_id)
	except ObjectDoesNotExist:
		return render(
			request, 
			'tags/tag_list.html', 
			context={'color_list': Color.objects.all(), 'tag_list': Tag.objects.all()}, 
			status=409)
	else:
		tag.color = color
		tag.save()
		return JsonResponse({'tag_id': tag.id, 'tag_color': tag.color})

@require_POST
@require_ajax
def update_tag_name(request, tag_id):
	try:
		tag = Tag.objects.get(pk=tag_id)
	except Tag.DoesNotExist:
		return render(
			request, 
			'tags/tag_list.html', 
			context={'color_list': Color.objects.all(), 'tag_list': Tag.objects.all()}, 
			status=409)
	else:
		form = TagForm(
			{'name': request.POST.get('tag_name')}, 
			instance=tag)
		if form.is_valid():
			form.save()
			template = render_to_string(
				'tags/tag_list.html', 
				{'color_list': Color.objects.all(), 'tag_list': Tag.objects.all()}, 
				request=request)
			return JsonResponse({
				'template': template, 
				'tag_id': tag.id, 
				'tag_name': tag.name
			})
		else:
			return JsonResponse(
				json.loads(form.errors.as_json()), 
				status=400)

@require_POST
@require_ajax
def create_note(request):
	form = NoteForm(request.POST)
	if form.is_valid():
		new_note = form.save()
		has_new_tags = False
		for tag_name in request.POST.get('tags'):
			try:
				tag = Tag.objects.get(name=tag_name)
			except ObjectDoesNotExist:
				tagForm = TagForm(name=tag_name)
				if tagForm.is_valid():
					tag = tagForm.save()
					has_new_tags = True
				else:
					continue
			new_note.tags.add(tag)
		if has_new_tags:
			tag_list_template = render_to_string(
				'tags/tag_list.html', 
				context={'color_list': Color.objects.all(), 'tag_list': Tag.objects.all()})
			node_list_template = render_to_string(
				'tags/node_list.html', 
				context={'note_list': Note.objects.all()})
			return JsonResponse({'tag_list': tag_list_template, 'node_list': node_list_template})
		else:
			return render(
				request, 
				'tags/note_list.html', 
				context={'note_list': Note.objects.all()})
	else:
		return JsonResponse(
			json.loads(form.errors.as_json()), 
			status=400)

@require_POST
@require_ajax
def remove_note_tag(request, note_id, tag_id):
	try:
		note = Note.objects.get(pk=note_id)
		tag = Tag.objects.get(pk=tag_id)
		tag.note_set.remove(note)
	except ObjectDoesNotExist:
		return render(
			request, 
			'tags/note_list.html', 
			context={'note_list': Note.objects.all()}, 
			status=409)
	else:
		return JsonResponse({'tag_id': tag.id})

@require_POST
@require_ajax
def delete_note(request, note_id):
	try:
		note = Note.objects.get(pk=note_id)
	except Note.DoesNotExist:
		return render(
			request, 
			'tags/note_list.html', 
			context={'note_list': Note.objects.all()}, 
			status=409)
	else:
		note.delete()
		return JsonResponse({'note_id': note.id})

tags/templates/tags/index.html
<!doctype html>
<html>
  <head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Deise Luise Wrasse">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Roboto:300,400,500|Roboto+Mono:500,700|Material+Icons">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "tags/css/main.css" %}">
  </head>
  <body class="display">
    <header class="ghost-center z1">
      <i class="header-icon material-icons ghost-center__content color-white js-push">menu</i>
      <span class="ghost-center__content text-title color-white">My Little Notes</span>
      <i class="header-icon material-icons color-white float-right">more_vert</i>
    </header>
    <div class="leftcol push-left area">
      <div class="area__scroll hover-scroll">
        <div class="leftcol__hold">
          <div class="area__searchbox area__l area__r">
            <div class="searchbox">
              <!--<i class="searchbox__icon searchbox__search material-icons">search</i>-->
              <div class="searchbox__fill">
                <input 
                  autocomplete="off" 
                  class="searchbox__input underline_primary js-tag-search js-search-input" 
                  novalidate="novalidate" 
                  placeholder="Search for a tag" />
                <button 
                  class="searchbox__icon searchbox__reset js-search-reset hidden"
                  data-search="js-tagbox">
                  <i class="material-icons icon icon_btn">close</i>
                </button>
              </div>
            </div>
          </div>
          <div class="area__content area__l taglist js-taglist">
            {% include "tags/tag_list.html" %}
          </div>
        </div>
      </div>
      <div class="rest">
        
      
      <button 
        class="area__action md-fab md-btn_mini md-btn_secondary js-form-action float-right" 
        data-form="js-tagform">
        <div class="action action_add">
          <div class="action__part action__h"></div>
          <div class="action__part action__v"></div>
        </div>
      </button>
      <div class="area__float-form float-form rest">
        
      </div>
      </div>
    </div>
    <main class="main push-left area">
      <div class="area__scroll main__scroll">
        <div class="area__searchbox area__l area__r">
          <div class="searchbox">
            <!--<i class="searchbox__icon searchbox__search material-icons">search</i>-->
            <div class="searchbox__fill">
              <input
                autocomplete="off"
                class="searchbox__input underline_primary js-note-search js-search-input" 
                novalidate="novalidate" 
                placeholder="Search for a note" />
              <button 
                class="searchbox__icon searchbox__reset js-search-reset hidden" 
                data-search="js-notebox">
                <i class="material-icons icon icon_btn">close</i>
              </button>
            </div>
          </div>
        </div>
        <div class="text-right area__r">
          <i class="material-icons js-view" data-view="list">view_stream</i>
          <i class="material-icons js-view" data-view="column">view_column</i>
          <i class="material-icons js-view" data-view="grid">view_quilt</i>
        </div>
        <div class="area__content area__l js-notelist">
          {% include "tags/note_list.html" %}
        </div>
      </div>
    </main>
    <div class="alert z3 color-bg-primary">
      <span class="alert__text text-body1 color-white"></span>
    </div>
    <div class="dialog hidden js-dialog">
      <div class="card dialog__window js-dialog-window">
        <div class="dialog__texts">
          <p class="dialog__title text-title js-dialog-title"></p>
          <p class="text-body1 js-dialog-text"></p>
        </div>
        <div class="dialog__buttons">
          <span class="md-btn md-btn_box text-button js-dialog-cancel js-dialog-btn"></span>
          <span class="md-btn md-btn_box text-button js-dialog-action js-dialog-btn"></span>
        </div>
      </div>
    </div>
    <div class="form hidden js-noteform">
      <div class="card form__window js-noteform-window">
        <div class="form__texts">
          <input class="text-body1 form__text js-noteform-link" placeholder="Note link" />
          <input class="text-body2 form__text js-noteform-title" placeholder="Note title" maxlength="100" />
          <textarea class="text-body1 form__text form__textarea js-noteform-text" maxlength="1000" placeholder="Note text"></textarea>
        </div>
        <div class="form__buttons">
          <span class="md-btn md-btn_box text-button js-noteform-cancel js-noteform-btn">cancel</span>
          <span class="md-btn md-btn_box text-button js-noteform-action js-noteform-btn">edit</span>
        </div>
      </div>
    </div>
    <script type="text/javascript" src="{% static "tags/js/jquery-3.2.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "tags/js/csrftoken.min.js" %}"></script>
    <script type="text/javascript" src="{% static "tags/js/index.js" %}"></script>
  </body>
</html>

tags/templates/tags/note_list.html
{% for note in note_list %}
<div class="noteview noteview_list area__r js-notebox">
<div class="notebox on-hover">
  <div class="note js-note">
    {% if note.link %}
    <a href="{{ note.link }}" title="Note link" class="js-note-link">
      <img 
        alt="Note link" 
        class="note__link" 
        src="https://www.google.com/s2/favicons?domain={{ note.link }}" 
        target="_blank" />
    </a>
    {% endif %}
    {% if note.title %}
    <p class="note__title js-note-title">{{ note.title }}</p>
    {% endif %}
    {% if note.text %}
    <p class="note__text js-note-text">{{ note.text }}</p>
    {% endif %}
  </div>
  <div class="notebox__icons on-hover__show">
    <!-- <i class="material-icons icon icon_btn">open_with</i> -->
    <i class="material-icons icon icon_btn js-note-edit">mode_edit</i>
    <i 
      class="material-icons icon icon_btn js-note-del" 
      data-url="{% url 'tags:delete-note' note.id  %}">delete_forever</i>
  </div>
  <div class="notebox__tags clearfix">
    {% for tag in note.tags.all %}
    <div class="tag notebox__tag js-notetag{{ tag.id }}">
      <span 
        class="tag__icon"
        style="color: {{ tag.color }}">#</span><!--
      --><span 
        class="tag__name js-notetag-name" 
        style="color: {{ tag.color }}">{{ tag.name }}</span><!--
      --><span 
        class="tag__close color-disabled js-notetag-remove" 
        data-url="{% url 'tags:remove-note-tag' note.id tag.id  %}">&times;</span>
    </div>
    {% endfor %}
  </div>
</div>
</div>
{% endfor %}

tags/templates/tags/tag_list.html
<!-- {% for tag in tag_list %}
<div class="on-hover clearfix tagbox js-tagbox">
  <div class="on-hover__show float-right">
    <div class="colors">
    	<i class="material-icons icon icon_btn colors__icon">color_lens</i>
    	<div class="colors__palette">
    		{% for color in color_list %}
    			<span 
    				class="colors__color js-tag-upd-color {% if color.id == tag.color.id %} colors__color_selected {% endif %}" 
    				style="background-color: {{ color }}" 
    				data-url="{% url 'tags:update-tag-color' tag.id color.id %}"></span>
    		{% endfor %}
    	</div>
    </div>
    <i class="material-icons icon icon_btn tagbox__delete-btn js-tag-del"
      data-url="{% url 'tags:delete-tag' tag.id  %}"
      >delete_forever</i>
  </div>
  <div class="chipedit rest js-tag{{ tag.id }}">
    <span 
      class="chipedit__item chipedit__bg text-code js-tag-color"
      style="background-color: {{ tag.color }}">{{ tag.name }}</span>
    <input 
      class="chipedit__item chipedit__input text-code color-white js-tag-input js-search-val"
      type="text" 
      data-url="{% url 'tags:update-tag-name' tag.id  %}"
      value="{{ tag.name }}" />
  </div>
</div>
{% endfor %} -->
{% for tag in tag_list %}
<div id="{{ tag.id }}" class="on-hover tagbox tag clearfix area__r js-tagbox">
	<span 
		class="tag__icon tagbox__icon float-left"
		style="color: {{ tag.color }}">#</span>
	<div class="tagbox__fill rest">
  	<input 
  		autocomplete="off"
  		class="tagbox__input tag__name js-tag-input" 
  		data-url="{% url 'tags:update-tag-name' tag.id  %}"
  		maxlength="50" 
  		disabled="disabled" 
  		style="color: {{ tag.color }}"
  		type="text" 
  		value="{{ tag.name }}" />
		<div class="on-hover__show tagbox__menu js-tag-menu">
			<i class="material-icons icon icon_btn colors__icon">color_lens</i>
			<div class="colors__palette">
    		{% for color in color_list %}
    			<span 
    				class="colors__color js-tag-upd-color {% if color.id == tag.color.id %} colors__color_selected {% endif %}" 
    				style="background-color: {{ color }}" 
    				data-url="{% url 'tags:update-tag-color' tag.id color.id %}"></span>
    		{% endfor %}
    	</div>
			<i class="material-icons icon icon_btn js-tag-edit">mode_edit</i><!--
			--><span 
    	class="tag__close color-disabled not-displayed js-tag-cancel js-tag-reset">&times;</span><!--
			--><i 
			class="material-icons icon icon_btn js-tag-del js-tag-reset" 
			data-url="{% url 'tags:delete-tag' tag.id  %}">delete_forever</i>
  	</div>
	</div>
</div>
{% endfor %}